version: "3.9"

services:
  baaastyserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true
volumes:
  baaastyserver: { }