version: "3.9"

services:
  baaastyserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - /home/baaastyde/baaastyserver-data:/baaastyserver
    restart: unless-stopped
    stdin_open: true
    tty: true